### ISSUE TITLE
Any way to retrieve historical wallet balance? 

### ISSUE THREAD

**Issue by myn** [deribit/deribit-api-clients#16]
Perhaps I am overlooking some of the documentation but I don't see  an API that gives you the ability to perform a query on historical balance?

I'm building an app that tracks a number of things, PNL over time being one of them based upon wallet balance.

Is this currently available or planned in current backlog?

Thanks

**Comment by lacksfish** [comment]
You have access to historical deposits and withdrawals (*) , but not the historical wallet balance. If that changes, I will post here with an update.


(*) https://docs.deribit.com/v2/#private-get_deposits | https://docs.deribit.com/v2/#private-get_withdrawals
