### ISSUE TITLE
how to install the python version

### ISSUE THREAD

**Issue by chengxx1986** [deribit/deribit-api-clients#18]
I have install the "setup.py" , but still have the following problem, how to solve these problems?Thank you!!!
1、what's the problem of the underline?
2、how can I get "YOUR_BEARER_TOKEN"

<img width="445" alt="image" src="https://user-images.githubusercontent.com/22536070/62467510-85efbe80-b7c6-11e9-8ce3-c55750f4a226.png">
<img width="751" alt="image" src="https://user-images.githubusercontent.com/22536070/62467731-01ea0680-b7c7-11e9-80c3-f052496bfb98.png">

**Comment by lacksfish** [comment]
I want to refer you to the solution of this issue: https://github.com/deribit/deribit-api-clients/issues/3

I'll copy paste it here for convenience:

```
pip3 install --user -U git+https://github.com/deribit/deribit-api-clients.git#egg=openapi_client\&subdirectory=python
```

**Comment by lacksfish** [comment]
You can retrieve a time-bound bearer token and refresh token from the following endpoint:
https://docs.deribit.com/v2/#public-auth

I'll update this post with a code example later.
