### ISSUE TITLE
Getting "unauthorized","code":13009

### ISSUE THREAD

**Issue by nhondong** [deribit/deribit-api-clients#19]
Hi, 

I request a bearer token via python from deribit.

`from __future__ import print_function
import requests
import time
import openapi_client
from openapi_client.rest import ApiException
from pprint import pprint
deribitauthurl = "https://www.deribit.com/api/v2/public/auth"

key = "api-key"
secret = "api-secret"

PARAMS = {'client_id': key, 'client_secret': secret, 'grant_type': 'client_credentials'}
r = requests.get(url=deribitauthurl, params=PARAMS)

data = r.json()
accesstoken = data['result']['access_token']

configuration = openapi_client.Configuration()

configuration.access_token = accesstoken

api_instance = openapi_client.AccountManagementApi(openapi_client.ApiClient(configuration))
sid = 56 # int | The user id for the subaccount
name = 'newUserName' # str | The new user name

api_response = api_instance.private_change_subaccount_name_get(sid, name)
pprint(api_response)
`
It seems, that the access token is incorrect. 

What i am doing wrong?

**Comment by chengxx1986** [comment]
I also have the same problem，have you solve this problem？

**Comment by nhondong** [comment]
> I also have the same problem，have you solve this problem？

No, currently not. 
Thought I am doing something wrong, but the bearer token seams to be valid.

**Comment by nhondong** [comment]
Just found out why the token was not working.
Params was missing the scope.

PARAMS = {'client_id': key, 'client_secret': secret, 'grant_type': 'client_credentials', 'scope': 'session:mysessionname'}

**Comment by lacksfish** [comment]
Great news, thank you for following up with your solution!

If you want, you can provide a code snippet with a minimal working example and I will make sure to include it in the README.md. Or simply pull request such a change, it would be very much appreciated.

**Comment by nhondong** [comment]
Here is a working example (getting current BTC Positions)
`from __future__ import print_function
import requests
import time
import openapi_client
from openapi_client.rest import ApiException
from pprint import pprint
deribitauthurl = "https://www.deribit.com/api/v2/public/auth"

key = "your API key"
secret = "your API secret"

PARAMS = {'client_id': key, 'client_secret': secret, 'grant_type': 'client_credentials', 'scope': 'session:tensorreport'}

#PARAMS = {'client_id': key, 'client_secret': secret, 'grant_type': 'client_credentials'}
r = requests.get(url=deribitauthurl, params=PARAMS)

# extracting data in json format
data = r.json()
accesstoken = data['result']['access_token']

configuration = openapi_client.Configuration()
# Configure Bearer authorization (Auth. Token): bearerAuth
configuration.access_token = accesstoken

# create an instance of the API class
api_instance = openapi_client.AccountManagementApi(openapi_client.ApiClient(configuration))
currency = 'BTC' # str |
#kind = 'kind_example' # str | Kind filter on positions (optional)

try:
    # Retrieve user positions.
    api_response = api_instance.private_get_positions_get(currency)
    pprint(api_response)
except ApiException as e:
    print("Exception when calling AccountManagementApi->private_get_positions_get: %s\n" % e)`
