### ISSUE TITLE
KeyError: 'variables' in configuration.get_host_from_settings() for python client

### ISSUE THREAD

**Issue by jDally987** [deribit/deribit-api-clients#2]
I'm trying to set the client to use the testnet with the python client. Looking at the configuration.py file, I assume that's done by setting the Configuration() object's `host` attribute to the testnet URL, which it looks like the `get_host_from_settings()` method is supposed to do:

```
config = Configuration()
config.host = config.get_host_from_settings(1)
```

But for some reason in the function body, it's looking for a key "variables" in the `server` dict (returned from `get_host_settings()`)? This throws a KeyError when I try to use that method to grab the testnet URL. Let me know if I'm doing something wrong but I can't figure out why that method wants to do that extra step. Would work fine if it just returned the URL as a string (it'd be even better if there was a simple method to call that sets the client to use the testnet url, or even just a parameter to pass in when creating Configuration() or something)

**Comment by lacksfish** [comment]
`get_host_from_settings()` returns an array of dictionaries (containing `url` and `description` keys)

A small change to your code will resolve your issue:

```python
config = Configuration()
config.host = config.get_host_settings()[1]['url']
```

**Comment by jDally987** [comment]
> `get_host_from_settings()` returns an array of dictionaries (containing `url` and `description` keys)
> 
> A small change to your code will resolve your issue:
> 
> ```python
> config = Configuration()
> config.host = config.get_host_settings()[1]['url']
> ```

Thanks, but it still throws it. It's looking for the variables key in the body of the method itself, so unless I stripped all that out of the `configuration` code manually it'd still do it. Also you still need to pass in something for the `index` parameter (`1` for the testnet entry)

**Comment by lacksfish** [comment]
`print(config.get_host_settings()[1]['url'])` will print the testnet URL as a string. You still need to set it to `config.host` and then refer your config when creating a api_client instance

```
config = Configuration()
config.host = config.get_host_settings()[1]['url']
client = api_client.ApiClient(config)
```

`get_host_settings()` does not take any function arguments, so if you pass `1` to it directly it will not do anything.

```
    def get_host_settings(self):
        """Gets an array of host settings

        :return: An array of host settings
        """
        return [
            {
                'url': "https://www.deribit.com/api/v2",
                'description': "main server",
            },
            {
                'url': "https://test.deribit.com/api/v2",
                'description': "No description provided",
            }
        ]
```

If you have a full code snippet that causes the error it would be much appreciated, then I can investigate better.

**Comment by jDally987** [comment]
@lacksfish whoops my bad, I didn't realize you were talking about get_host_settings, I was referring to get_host_FROM_settings. Lol. Your way looks much better though, don't know why I didn't just do that. Just kinda confused still what get_host_FROM_settings() is for though.
