### ISSUE TITLE
How to install in Python

### ISSUE THREAD

**Issue by PietStevens** [deribit/deribit-api-clients#23]
Maybe someone can help. I can't get the openapi_client to install in Python. The command 
pip3 install --user -U git+https://github.com/deribit/deribit-api-clients.git#egg=openapi_client\&subdirectory=python
that was mentioned before doesn't work.

**Comment by PietStevens** [comment]
Never mind. I copied the openapi_client folder to my work directory and now it works fine.

**Comment by lacksfish** [comment]
https://github.com/deribit/deribit-api-clients/issues/18
