### ISSUE TITLE
pip3 cannot uninstall

### ISSUE THREAD

**Issue by TheLegendAli** [deribit/deribit-api-clients#28]
I cannot do pip3 uninstal l 'openapi-client

**Comment by Xavier59** [comment]
We can't help you if you don't give us the output of your command ...

Install directly from this git repostiroy :
`pip3 install "git+https://github.com/deribit/deribit-api-clients.git#egg=pkg_dir&subdirectory=python"`

Uninstall : 
`pip3 uninstall openapi-client`

Worked for me : 
`Successfully uninstalled openapi-client-1.0.0`

**Comment by TheLegendAli** [comment]
This is the output i get

`pip3 uninstall openapi-client
Can't uninstall 'openapi-client'. No files were found to uninstall.`

**Comment by Xavier59** [comment]
Are you sure it's installed ?

Check with python
`python -c "import openapi_client"`, output should be `ImportError: No module named openapi_client` if it's not installed
or with pip3
`pip3 show openapi_client` (no output = not installed) or `pip3 list` to see all installed packaged

If it is indeed installed, try running `pip3 install --upgrade pip` and then uninstalling openapi-client again

**Comment by TheLegendAli** [comment]
`pip3 install --upgrade pip' was the problem...wow rookie mistake....
