### ISSUE TITLE
How to install "openapi_client"

### ISSUE THREAD

**Issue by cc345** [deribit/deribit-api-clients#3]
I am looking to use the "openapi_client" that can be seen [here](https://github.com/deribit/deribit-api-clients/tree/master/python#installation--usage), only problem is there isn't proper documentation on how to install it? The only thing there is the default code for installing something with pip and git+, the text reads: _pip install git+https://github.com/GIT_USER_ID/GIT_REPO_ID.git_

That doesn't do anything. Can someone tell me the actual name of the openapi_client so that I may use it and install it? I have already tried "pip install openapi_client" which did nothing.

**Comment by lacksfish** [comment]
Lets say you want to run a script which you named `trading_logic.py` which depends on the client library.

You are in the folder with your python script. Copy the `openapi_client` folder into the same dir as your python script like so:

```
trading_logic.py
|
---- openapi_client/api_client.py
---- openapi_client/configuration.py
---- openapi_client/any_other_file.py
```

In `trading_logic.py`, you can then do:

```python
import openapi_client.api_client as api_client
import openapi_client.configuration as configuration
import openapi_client.api.private_api as private_api
import openapi_client.api.public_api as public_api
```

**Comment by lacksfish** [comment]
If you're required to go through pip, you can do:
```
pip3 install --user -U git+https://github.com/deribit/deribit-api-clients.git#egg=openapi_client\&subdirectory=python
```

**Comment by lacksfish** [comment]
Closing this for now :)

**Comment by srqBTC** [comment]
Hi I am running into the same problem, I can't import openapi_client.
I am using Spyder (Python 3.8) downloaded via Anaconda.
I already have setuptools intalled but still can't import openapi_client.
Could you please help, I can't find many answers out there?
Thank you very much.
