### ISSUE TITLE
Where is the original OpenAPI file?

### ISSUE THREAD

**Issue by olibre** [deribit/deribit-api-clients#33]
Using [OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator) is awesome. :heart_eyes: 

But how can I produce the same results using the OpenAPI input file?
I have searched that kind of file on deribit.com website but nothing. :disappointed:  

1. Is that OpenAPI file publicly available?
2. Can you add in the README where to find that OpenAPI file?

**Comment by lacksfish** [comment]
1. Unfortunately that is not publicly available.
2. See 1.
