### ISSUE TITLE
Publish to npm?

### ISSUE THREAD

**Issue by rnons** [deribit/deribit-api-clients#4]
The [README](https://github.com/deribit/deribit-api-clients/tree/master/javascript) says
> npm install deribit_api --save

But I can't find `deribit_api` on npm

**Comment by lacksfish** [comment]
You can install the v1 API client via npm [already](https://github.com/deribit/deribit-api-js#installation). This is a different project repo though.

This repo's v2 API client will be made available via npm in due time.
