### ISSUE TITLE
Can't install package properly - python 

### ISSUE THREAD

**Issue by rafaelyahlomi** [deribit/deribit-api-clients#49]
I'm trying to run the following CMD but none of them is working:

pip install git+http://github.com/deribit/deribit-api-clients/python@master.git (error: doesn't recognize the folder)
pip install http://github.com/deribit/deribit-api-clients/tree/master/python (error: can't determine archive)

I even downloaded the folder, unzipped it and run:
python C:/Users/****/Downloads/deribit-api-clients-master/deribit-api-clients-master/python/setup.py install --user

It did install the package, but as an EGG file. I can see the package in my package list (look below)
![egg](https://user-images.githubusercontent.com/11321861/82352977-7402a380-9a07-11ea-8f8b-c89c53cca549.PNG)
, but still can't import it properly. Then I tried also the run easy_install command as follow:
python -m easy_install C:\Users\****\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\openapi_client-1.0.0-py3.7.egg

But again - still can't import it.

Any suggestions how can I download it properly? 

Thanks,

Rafael

**Comment by lacksfish** [comment]
If you're using pip, you can do:
```
pip3 install --user -U git+https://github.com/deribit/deribit-api-clients.git#egg=openapi_client\&subdirectory=python
```

**Comment by rafaelyahlomi** [comment]
Thanks for your help. However when I run your command I receive the attached error.
![cl](https://user-images.githubusercontent.com/11321861/82584382-199b4b80-9b9d-11ea-94e2-d232f0614c01.PNG)

**Comment by lacksfish** [comment]
>On Windows, you must place the URL in double quotes, or you'll get an error "'subdirectory' is not recognized as an internal or external command". 
~ https://stackoverflow.com/a/19516714

On Windows, sometimes things are a little different. I'm also thinking the `\` could be an issue

So I'm guessing this could work:


    pip install -e "git+https://github.com/deribit/deribit-api-clients.git#egg=openapi_client&subdirectory=python

**Comment by rafaelyahlomi** [comment]
Great, thanks. Now it works properly. Many thanks for your help.
