### ISSUE TITLE
csharp project can not be loaded because of comments in csproj file

### ISSUE THREAD

**Issue by psollberger** [deribit/deribit-api-clients#6]
The CSharp Solution can not be opened. There are the following errors:

...\deribit-api-clients\csharp\src\Org.OpenAPITools\Org.OpenAPITools.csproj : error  : The project file could not be loaded. An XML comment cannot contain '--', and '-' cannot be the last character. Line 5, position 494.  ...\deribit-api-clients\csharp\src\Org.OpenAPITools\Org.OpenAPITools.csproj

...\deribit-api-clients\csharp\src\Org.OpenAPITools.Test\Org.OpenAPITools.Test.csproj : error  : The project file could not be loaded. An XML comment cannot contain '--', and '-' cannot be the last character. Line 5, position 494.  ...\deribit-api-clients\csharp\src\Org.OpenAPITools.Test\Org.OpenAPITools.Test.csproj

**Comment by lacksfish** [comment]
I think the correct folder to look at would be `Org.OpenAPITools` and not `Org.OpenAPITools.Test`. The folder you mentioned contains only unit test boilerplates as far as I can tell.

Also, in the root of the `csharp` folder you will find the file `Org.OpenAPITools.sln`. Is it possible to open this file with, for example, a recent version of Visual Studio? That'd be an alternative option.

**Comment by lacksfish** [comment]
I think you can literally just delete [this line in the comments](https://github.com/deribit/deribit-api-clients/blob/master/csharp/src/Org.OpenAPITools/Org.OpenAPITools.csproj#L5) and you should be good to go.

**Comment by psollberger** [comment]
I opened the mentioned sln file with Visual Studio 2019 Community Edition
And yes. Removing the comments in the csproj files works as a workaround.

But my intention was that this is fixed in the repository so everyone can benefit,
But i'm personally ok with just removing the comments myself.

**Comment by lacksfish** [comment]
It's worth the change tbh, will commit the change as it is definitely helpful. Perhaps just string replacing `--` to `##` can help. Maybe there's also an escape character and it'd be something that is better fixed upstream in openAPI generator.

Either way, if you'd want to pull request a character change I'd happily merge it.
